---
- name: Configuring Docker-Server
  hosts: docker-server
  become: yes
  roles:
    - docker_server

- name: Configuring NG-SIEM
  hosts: ng-siem
  become: yes
  roles:
    - ng-siem

- name: Configure Kali
  hosts: kali
  become: yes
  roles:
    - kali

- name: Configuring victim PC
  hosts: victim
  become: yes
  roles:
    - victim

- name: Configure to all systems (logging, hosts, etc)
  hosts: all
  become: true
  roles:
    - all

- name: Changing syslog-ng on man
  hosts: man
  become: yes
  roles:
    - man

- name: set up command logging
  hosts: 
    - routers
    - hosts
  become: yes
  roles:
    - role: sandbox-logging
      slf_destination_port: '{% if hostvars["man"] is defined -%} 514 {%- else -%} 515 {%- endif %}'
      when: ansible_system == "Linux"
